name: global_repository
description: A new Flutter package project.
version: 0.0.1
# homepage:
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  path: ^1.8.0
  synchronized: ^3.0.0
  flutter_markdown: ^0.7.4+3
  get: ^4.1.3
  # launcher url
  url_launcher: ^6.0.18
  responsive_framework: ^1.0.0
  signale: ^0.0.10
  # 提供路径访问
  permission_handler: 6.0.0
  window_manager: ^0.3.0
  dio: ^5.4.3+1
  intl: ^0.20.2
  xterm:
    git:
      url: https://github.com/TerminalStudio/xterm.dart
      ref: master

  retrofit: ^4.4.1
  json_annotation: ^4.9.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_annotation: ^4.5.0
  retrofit_generator: ^9.3.0 # for Dart 3.3 use ^9.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.5
  intl_utils: ^2.8.7

flutter:
  assets:
    - assets/icon/
dependency_overrides:
  signale:
    git:
      url: https://github.com/nightmare-space/signale
